// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc1GoD7tsMnpZwrVtxUgUTbYDhjVzG2j0',
    appId: '1:519186774669:web:25f21e557d9c71683940c4',
    messagingSenderId: '519186774669',
    projectId: 'android-d03a9',
    authDomain: 'android-d03a9.firebaseapp.com',
    storageBucket: 'android-d03a9.firebasestorage.app',
    measurementId: 'G-0BLXY03GW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j3i3fEAxeka7XLzbKO11esagZH4ULHg',
    appId: '1:519186774669:android:f05db1f49a1079ac3940c4',
    messagingSenderId: '519186774669',
    projectId: 'android-d03a9',
    storageBucket: 'android-d03a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdNjIr55jUvphLLm4bsWjKDuavkDOM57c',
    appId: '1:519186774669:ios:239bbdb32ae7daf03940c4',
    messagingSenderId: '519186774669',
    projectId: 'android-d03a9',
    storageBucket: 'android-d03a9.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdNjIr55jUvphLLm4bsWjKDuavkDOM57c',
    appId: '1:519186774669:ios:239bbdb32ae7daf03940c4',
    messagingSenderId: '519186774669',
    projectId: 'android-d03a9',
    storageBucket: 'android-d03a9.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc1GoD7tsMnpZwrVtxUgUTbYDhjVzG2j0',
    appId: '1:519186774669:web:fa16eee4357a7e0c3940c4',
    messagingSenderId: '519186774669',
    projectId: 'android-d03a9',
    authDomain: 'android-d03a9.firebaseapp.com',
    storageBucket: 'android-d03a9.firebasestorage.app',
    measurementId: 'G-4TF088V3H5',
  );
}
